### ISSUE TITLE
Table of Contents: Broken Links

### ISSUE THREAD

**Issue by jthomas** [ibm-cloud-docs/api-management#2]
Visiting this page (https://console.bluemix.net/docs/api-management/manage_apis.html) from the Cloud Functions docs, all the links in the left-hand menu are broken. 

For example "Create APIs from Cloud Functions Actions" links to...
https://console.bluemix.net/docs/manage_openwhisk_apis.html#manage_openwhisk_apis
rather than
https://console.bluemix.net/docs/api-management/manage_openwhisk_apis.html#manage_openwhisk_apis

It looks like the `api-management` path in the links are all missing.

**Comment by ejbowling** [comment]
@jthomas Thanks for catching this - ToC is fixed now.

**Comment by KentHall2018** [comment]
repo is being deprecated
