### ISSUE TITLE
Should note that api-management is deprecated

### ISSUE THREAD

**Issue by davetropeano** [ibm-cloud-docs/api-management#4]
The API Management doc pages (https://cloud.ibm.com/docs/api-management?topic=api-management-getting-started) link to the API Gateway doc page (https://cloud.ibm.com/docs/services/api-gateway) but does not mention that API Gateway itself is deprecated as of 31-Aug-2021 and will be shut off 31-Aug-2022.

I suggest that we put a small header on all the /docs/api-management pages saying that API Gateway itself is deprecated. The deprecation announcement is here: https://community.ibm.com/community/user/integration/blogs/newton-piccone2/2021/08/31/deprecation-of-the-ibm-cloud-api-gateway-service-e

**Comment by ejbowling** [comment]
Published:
![image](https://user-images.githubusercontent.com/10119356/164279666-6bdea513-39d6-43a0-955b-1f2be92f9ae4.png)
